### PR TITLE
Add JavaScript support.

### PR DESCRIPTION
**Pull request by vincedani**
Dear Maintainers,

The pull request contains an extension with basic JavaScript language support.

Also contains one unresolved `TODO` section [here](https://github.com/perses-project/perses/compare/master...vincedani:js_support?expand=1#diff-45ce4a2a0f775a42bd7624f7b49a065a2485536d14b34db10138c72814ba53baR83).

### CODE REVIEW

**Comment by chengniansun** [comment]
Hi Daniel,

Thank you for your PR. I will review it as soon as possible. Currently I am facing several difficulties merging your PRs, mostly from my side.

1. This is a mirror of our internal repo, and we periodically push our internal changes to this repo. I have not thought about how to merge public PRs into our internal repo.
2. I am very busy this term on teaching, and have limited time on programming. I should be able to have more time after April. 

Meanwhile, regarding your PR, 

1. Can you run ./scripts/presubmit.sh to clean up your PRs. 
2. Can you add tests to your code? One system test case in [here](https://github.com/perses-project/perses/tree/master/test/org/perses/benchmark_toys), and several unit tests for the code that you changed. 

Thanks.

**Comment by chengniansun** [comment]
Just want to update you about an issue in the PNF normalizer.

I tried to include the javascript grammar into Perses, however, the PNFied grammar was rejected by Antlr due to left recursions. This bug will take a while to fix.

**Comment by vincedani** [comment]
Hi @chengniansun,

Thanks for the suggestions, I'll update the PR soon with the results from `./scripts/presubmit.sh` and the tests.

**Comment by chengniansun** [comment]
Thanks, @vincedani for your contribution.

Due to our current release workflow, we could not take external contributions for now. I hope we can fully migrate to this public repo by the end of this year.

If you have any problem or feature request about perses, please do not hesitage to open an issue.

Best.
Chengnian.

**Pull request closed without merging**
